### PR TITLE
feat: first eslint rule -> suggest to add json response

### PR DESCRIPTION
**Pull request by itelo**
I'm testing adding `eslint` to check if the `jsonResponse` is inside the `route_spec` object. I will try to use typescript eslint later (it's capable of testing even type lol)

### CODE REVIEW

**Review by seveibar — APPROVED** [review]
can you remove the `yarn.lock`? Otherwise I think this is pretty good

**Comment by seveibar** [comment]
@itelo sorry for the delay. Yea sorry I might have seen a package-lock.json or thought I saw one- my mistake

**Comment by itelo** [comment]
@seveibar  Do I need to change something for this new package also release?

**Comment by seveibar** [comment]
no i think this is good to go! When you merge you might want to add `fix: ` or `feat: ` as usual

**Pull request merged**
