### PR TITLE
feat: skip body validation on get request

### PR DESCRIPTION
**Pull request by itelo**

### CODE REVIEW

**Comment by razor-x** [comment]
Nice! This is a breaking change, but we could put it behind a new option so it's not breaking: `validateGetRequestBody` (default true)

**Review by seveibar — APPROVED** [review]
lgtm, not a bad idea to make non-breaking as Evan suggested

**Comment by razor-x** [comment]
@itelo https://github.com/seamapi/nextlove/pull/67

**Comment by razor-x** [comment]
I actually PRed into your PR, but since you closed this I can take over. Thanks for getting this started even though I asked about the  feature. Finding the correct line to change was most of the work 😁

**Pull request closed without merging**
